<?php

/**
 * @file
 * Check for known security issues in Composer libraries.
 */

/**
 * Implements hook_composer_dependencies_install().
 */
function composer_manager_sa_composer_dependencies_install() {
  // This hook is only called with Drush, so we know this function is safe to
  // call.
  composer_manager_sa_print();
}

/**
 * Implements hook_cron().
 */
function composer_manager_sa_cron() {
  // If the data is still in the cache, this will not do anything beyond a
  // cache_get() call.
  composer_manager_sa_vulnerabilities(composer_manager_lock_file());
}

/**
 * Check for security advisories against Composer libraries.
 *
 * @param string $lock_file
 *   The URI to the composer.lock file.
 *
 * @return string
 *   The formatted security advisory report. This will also contain a result if
 *   no issues are found.
 */
function composer_manager_sa_check($lock_file) {
  $vulnerabilities = composer_manager_sa_vulnerabilities($lock_file);
  return composer_manager_sa_formatted($lock_file, $vulnerabilities);
}

/**
 * Generate an HTML-formatted report for an array of vulnerabilities.
 *
 * @param string $lock_file
 *   The URI to the composer.lock file.
 * @param array $vulnerabilities
 *   An array of security vulnerabilities.
 *
 * @return string
 *   Formatted output of the report, or an empty string.
 */
function composer_manager_sa_formatted($lock_file, array $vulnerabilities) {
  $output = '';
  foreach ($vulnerabilities as $library => $vulnerability) {
    $output .= '<li><code>' . $library . '</code>: ';
    foreach ($vulnerability['advisories'] as $advisory) {
      $output .= l($advisory['cve'], $advisory['link'], array('attributes' => array('target' => '_blank')));
      $output .= ' (' . $advisory['title'] . ') ';
    }
    $output .= '</li>';
  }

  return (!empty($output)) ? '<ul>' . $output . '</ul>' : '';
}

/**
 * Find any known vulnerabilities in a composer.lock file.
 *
 * Vulnerability reports are cached for one hour, based on the contents of
 * composer.lock.
 *
 * @param string $lock_file
 *   The URI to the composer.lock file.
 * @param bool $force_refresh
 *   (optional) Set to TRUE to force a refresh of cached data.
 *
 * @return array
 *   An array of known security issues, or an empty array if all libraries
 *   passed.
 */
function composer_manager_sa_vulnerabilities($lock_file, $force_refresh = FALSE) {
  // 'drush composer-manager' doesn't run a full bootstrap, so on install and
  // update the Composer autoloader may not be registered.
  composer_manager_register_autoloader();

  if ($force_refresh || (!empty($lock_file) && !$vulnerabilities = composer_manager_sa_cache($lock_file))) {
    $vulnerabilities = &backdrop_static('composer_manager_sa_cache');
    if (!file_exists($lock_file)) {
      backdrop_set_message(t('The composer.lock file could not be found at @path.', ['@path' => $lock_file]), 'error');
      return [];
    }
    $lock_data = json_decode(file_get_contents($lock_file), TRUE);
    // @todo: Consider checking dev dependencies as well, but this may require
    // a more complex UI to allow users to ignore advisories for dev
    // dependencies on production sites OR just check if they are installed.
    // $packages = array_merge($lock_data['packages'], $lock_data['packages-dev']);
    $packages = $lock_data['packages'];
    $package_names = [];
    foreach ($packages as $package) {
      $package_names[] = $package['name'];
    }
    // Retrieve and check the Packagist.org API security advisories.
    $vulnerabilities = [];
    if (!empty($package_names)) {
      $query = http_build_query(['packages' => $package_names], '', '&', PHP_QUERY_RFC3986);
      $response = backdrop_http_request('https://packagist.org/api/security-advisories/?' . $query);
      if ($response->code == 200) {
        $data = json_decode($response->data, TRUE);
        foreach ($packages as $package) {
          if (isset($data['advisories'][$package['name']])) {
            foreach ($data['advisories'][$package['name']] as $advisory) {
              // Check if the installed version is affected. The equal sign may
              // be implicit, so we have to check for that last -- if there is
              // no operator, we will treat it as an equality check.
              $comparison_operators = [
                '<=',
                '>=',
                '<',
                '>',
                '=',
              ];
              $version_ranges = explode('|', $advisory['affectedVersions']);
              foreach ($version_ranges as $version_range) {
                $package_is_affected = FALSE;
                $versions_affected = explode(',', $version_range);
                foreach ($versions_affected as $version_constraint) {
                  // Set to true as we go through the constraints within a
                  // particular range if the version is affected by any of them.
                  // If the version is still marked as affected after checking
                  // the entire range, we can stop processing the rest of the
                  // ranges for this advisory.
                  foreach ($comparison_operators as $operator) {
                    if (strpos($version_constraint, $operator) === 0) {
                      $version_constraint = trim($version_constraint, '<>=');
                      break;
                    }
                  }
                  $package_version = ltrim($package['version'], 'v');
                  if (version_compare($package_version, $version_constraint, $operator)) {
                    $package_is_affected = TRUE;
                  }
                  else {
                    // If the package is outside of a version constraint within
                    // a particular range, it is not affected by the advisory,
                    // even if it is within other constraints in the same
                    // version range.
                    $package_is_affected = FALSE;
                    break;
                  }
                }
                if ($package_is_affected) {
                  $vulnerabilities[$package['name']]['version'] = $package['version'];
                  $vulnerabilities[$package['name']]['advisories'][] = [
                    'cve' => $advisory['cve'] ?: $advisory['advisoryId'],
                    'title' => $advisory['title'],
                    'link' => $advisory['link'],
                  ];
                  break;
                }
              }
            }
          }
        }
      }
    }
    cache_set(composer_manager_sa_cache_cid($lock_file), $vulnerabilities, 'cache', 3600);
  }

  return $vulnerabilities;
}

/**
 * Return the cached security advisory report.
 *
 * @param string $lock_file
 *   The URI to the composer.lock file.
 *
 * @return array|NULL
 *   The array of cached vulnerabilities, or FALSE if no data is in the cache.
 */
function composer_manager_sa_cache($lock_file) {
  $vulnerabilities = &backdrop_static(__FUNCTION__);

  // If there are no vulnerabilities this is an empty array, so we have to use
  // is_array() to check to see if we are cached or not.
  if (is_array($vulnerabilities)) {
    return $vulnerabilities;
  }

  if (empty($lock_file)) {
    return FALSE;
  }
  $cid = composer_manager_sa_cache_cid($lock_file);
  if ($cached = cache_get($cid)) {
    $vulnerabilities = $cached->data;
  }

  return $vulnerabilities;
}

/**
 * Return the cache ID for a lock file URI.
 *
 * @param string $lock_file
 *   The URI to the composer.lock file.
 *
 * @return string
 *   The cache ID, or an empty string if the lock file is empty.
 */
function composer_manager_sa_cache_cid(string $lock_file = '') {
  $cid = (!empty($lock_file) && file_exists($lock_file)) ? md5(file_get_contents($lock_file)) : '';
  return $cid;
}
